/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modules;

import Components.*;
import config.DesignConstants;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author HP
 */
public class DoctorsPage extends javax.swing.JFrame {


    public DoctorsPage() {

        initComponents();
        
        Object[][] formStructure = {
            {"Id", "IntegerField", null, null},
            {"Name", "TextField", null, null},
            {"Specialty", "ComboBox", new String[]{"Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Other"}, null},
            {"Phone_Number", "TextField", null, null},
            {"Email", "TextField", null, null},
            {"Gender", "RadioButton", new String[]{"Male", "Female"}, null},
            {"Years_of_Experience", "IntegerField", null, null},
            {"Status", "ComboBox", new String[]{"Active", "Inactive"}, null},
            {"Start_Time", "TimeField", null, null},
            {"End_Time", "TimeField", null, null}
        };

         PageHeader pageHeader = new PageHeader(
            "Doctor",
            formStructure,
            "/reports/DoctorsReport.jrxml"
        );
        
        final String[] DOCTORS_COLUMNS = {
            "ID", "Name", "Specialty", "Phone Number", "Email", "Gender", "Years of Experience", "Status", "Start Time", "End Time", "Action"
        };
        Table tablePanel = new Table(DOCTORS_COLUMNS, "doctors", formStructure);
        pageHeader.setTable(tablePanel, "doctors");

        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

        pageHeader.setMaximumSize(new Dimension(Integer.MAX_VALUE, pageHeader.getPreferredSize().height));
        tablePanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));

        mainPanel.add(pageHeader);
        mainPanel.add(tablePanel);

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(mainPanel, BorderLayout.CENTER);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(DesignConstants.FRAME_SIZE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
